### PR TITLE
Mads work

### PR DESCRIPTION
**Pull request by madhurireddy**
Hi Patsy,

I added a grid on the instructors page and modified css. Please review.

Thanks,
Madhuri

### CODE REVIEW

**Comment by PatsyKlotz** [comment]
Did you check that the styles are applying? The CSS does not appear to be working.

**Comment by madhurireddy** [comment]
Did you checkout the mads-work branch? How are you verifying? They are
still sitting in my branch and are not merged to master or the gh-pages
branch.

On Tue, Dec 8, 2015 at 8:31 AM, PatsyKlotz notifications@github.com wrote:

> Did you check that the styles are applying? The CSS does not appear to be
> working.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PatsyKlotz/client-site/pull/10#issuecomment-162936963
> .

## 

Madhuri
Direct:206-910-6237

**Comment by madhurireddy** [comment]
Okay, this how it looks.

On Tue, Dec 8, 2015 at 11:02 AM, Madhuri Devidi madhuri.devidi@gmail.com
wrote:

> Did you checkout the mads-work branch? How are you verifying? They are
> still sitting in my branch and are not merged to master or the gh-pages
> branch.
> 
> On Tue, Dec 8, 2015 at 8:31 AM, PatsyKlotz notifications@github.com
> wrote:
> 
> > Did you check that the styles are applying? The CSS does not appear to be
> > working.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/PatsyKlotz/client-site/pull/10#issuecomment-162936963
> > .
> 
> ## 
> 
> Madhuri
> Direct:206-910-6237

## 

Madhuri
Direct:206-910-6237

**Comment by PatsyKlotz** [comment]
I have the home page grid layout done.

**Comment by madhurireddy** [comment]
I worked on the sticky header. Could you please take care of the side nav
styling.
 Thanks,
Madhuri

On Tue, Dec 8, 2015 at 2:07 PM, PatsyKlotz notifications@github.com wrote:

> I have the home page grid layout done.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PatsyKlotz/client-site/pull/10#issuecomment-163033248
> .

## 

Madhuri
Direct:206-910-6237

**Pull request merged**
