### PR TITLE
Patsy work

### PR DESCRIPTION
**Pull request by PatsyKlotz**
I have added the page layouts for the home and facilities pages. Please review. Thanks!

### CODE REVIEW

**Comment by madhurireddy** [comment]
Awesome!

**Comment by madhurireddy** [comment]
Hi Patsy,

I just added two layouts for the instructors page and contact us page.
Please check them out. Instructors page and Facilites page both have the
same sub nav and content so we are good. We can choose either.

They are merged to master. Sorry, I merged them and then realized I had to
send a pull request first.

Thanks,
Madhuri

On Mon, Nov 30, 2015 at 8:29 AM, PatsyKlotz notifications@github.com
wrote:

> I have added the page layouts for the home and facilities pages. Please
> 
> ## review. Thanks!
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/PatsyKlotz/client-site/pull/3
> Commit Summary
> - layout fac page
> - page layout home
> 
> File Changes
> - _A_ resources/page-layout-facilities.pdf
>   https://github.com/PatsyKlotz/client-site/pull/3/files#diff-0 (0)
> - _A_ resources/page-layout-home.pdf
>   https://github.com/PatsyKlotz/client-site/pull/3/files#diff-1 (0)
> 
> Patch Links:
> - https://github.com/PatsyKlotz/client-site/pull/3.patch
> - https://github.com/PatsyKlotz/client-site/pull/3.diff
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PatsyKlotz/client-site/pull/3.

## 

Madhuri
Direct:206-910-6237

**Comment by PatsyKlotz** [comment]
I had no idea what you are/were working on. There is no indication in the Trello board. It would be very helpful if you indicate what your are/were working on. Cheri asked us to break down the tasks on a much smaller scale, e.g., "working on header."

**Comment by madhurireddy** [comment]
Can you work on home page semantic html and I almost finished the
instructors semantic html

On Mon, Nov 30, 2015 at 1:44 PM, PatsyKlotz notifications@github.com
wrote:

> I had no idea what you are/were working on. There is no indication in the
> Trello board. It would be very helpful if you indicate what your are/were
> working on. Cheri asked us to break down the tasks on a much smaller scale,
> e.g., "working on header."
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PatsyKlotz/client-site/pull/3#issuecomment-160771313.

## 

Madhuri
Direct:206-910-6237

**Comment by madhurireddy** [comment]
I've been trying to setup a time to discuss the plan but it never happened.
If we talk and then do the work it is better.

On Mon, Nov 30, 2015 at 2:02 PM, Madhuri Devidi madhuri.devidi@gmail.com
wrote:

> Can you work on home page semantic html and I almost finished the
> instructors semantic html
> 
> On Mon, Nov 30, 2015 at 1:44 PM, PatsyKlotz notifications@github.com
> wrote:
> 
> > I had no idea what you are/were working on. There is no indication in the
> > Trello board. It would be very helpful if you indicate what your are/were
> > working on. Cheri asked us to break down the tasks on a much smaller scale,
> > e.g., "working on header."
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/PatsyKlotz/client-site/pull/3#issuecomment-160771313
> > .
> 
> ## 
> 
> Madhuri
> Direct:206-910-6237

## 

Madhuri
Direct:206-910-6237

**Comment by PatsyKlotz** [comment]
I have sent emails attempting to arrange a collaborative effort. I had no indication that you were working on any part of the project until you added layouts two hours ago.

**Comment by PatsyKlotz** [comment]
We are suppose to write HTML for the two pages in which we created layouts. I created layouts for the home and facilities pages. So, I was working on the Facilities page before you merged your Instructors page to the master. So, I guess we will be turning in the Facilities page and the Instructors page.

**Comment by madhurireddy** [comment]
No problem! I can work on the home page and if you have home page already
we can merge it. More is ok.

On Mon, Nov 30, 2015 at 4:34 PM, PatsyKlotz notifications@github.com
wrote:

> We are suppose to write HTML for the two pages in which we created
> layouts. I created layouts for the home and facilities pages. So, I was
> working on the Facilities page before you merged your Instructors page to
> the master. So, I guess we will be turning in the Facilities page and the
> Instructors page.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PatsyKlotz/client-site/pull/3#issuecomment-160808884.

## 

Madhuri
Direct:206-910-6237

**Comment by PatsyKlotz** [comment]
Can we agree to work on two pages? Two pages gives us time to ensure that there are no errors. Time for testing. With any extra time, I would prefer to work on the style guide for extra credit. Keeping it streamlined ensures better quality; therefore, better grade. I can switch to the home page.

**Comment by PatsyKlotz** [comment]
Please work on just one page. The Instructor page is fine. I will switch to the Home page.

**Comment by madhurireddy** [comment]
just saw your email..we can do whatever you want

On Mon, Nov 30, 2015 at 4:41 PM, PatsyKlotz notifications@github.com
wrote:

> Please work on just one page. The Instructor page is fine. I will switch
> to the Home page.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PatsyKlotz/client-site/pull/3#issuecomment-160810008.

## 

Madhuri
Direct:206-910-6237

**Comment by PatsyKlotz** [comment]
I added the Home page html and a smaller logo. Please review. In the interest of "mobile first" and thinking modular, can we use the same header (with appropriate adjustments), footer, and aside? Please see the home page. Thank you!

**Comment by PatsyKlotz** [comment]
Please validate your code. Thanks! I just did. Had an extra </p>. It's been removed and I re-validated the HTML.

**Pull request merged**
